spring:
  application:
    name: sso-backend
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: 215b5640-18a9-4579-85f0-dee13df57b61
            client-secret: tuz8Q~Zda7W6IEDsnrucsYvol4QecDkM7J68lbu~
            scope:
              - openid
              - profile
              - email
              - https://graph.microsoft.com/User.Read
              - https://graph.microsoft.com/User.ReadBasic.All
            redirect-uri: http://localhost:8080/login/oauth2/code/
            client-name: Azure AD
        provider:
          azure:
            authorization-uri: https://login.microsoftonline.com/3dbd7e58-e2ea-40b8-bb5a-3ea2038c9535/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/3dbd7e58-e2ea-40b8-bb5a-3ea2038c9535/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/oidc/userinfo
            jwk-set-uri: https://login.microsoftonline.com/3dbd7e58-e2ea-40b8-bb5a-3ea2038c9535/discovery/v2.0/keys
            user-name-attribute: sub
            issuer-uri: https://login.microsoftonline.com/3dbd7e58-e2ea-40b8-bb5a-3ea2038c9535/v2.0

server:
  port: 8080

cors:
  allowed-origins: http://localhost:4200
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true